services:
  - type: web
    name: nexus-hub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: nexusdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: UNIT_DELETE_SECRET_KEY
        sync: false
      - key: ACTIVATION_LINK
        sync: false
      - key: FLASK_ENV
        value: production
databases:
  - name: nexusdb
    databaseName: nexus
    user: postgres